# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sf.substreams.rpc.v2 import service_pb2 as sf_dot_substreams_dot_rpc_dot_v2_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sf/substreams/rpc/v2/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamStub:
    """Stream is the primary service for consuming Substreams data. It provides a real-time
    and historical stream of blockchain blocks processed through Substreams modules.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Blocks = channel.unary_stream(
                '/sf.substreams.rpc.v2.Stream/Blocks',
                request_serializer=sf_dot_substreams_dot_rpc_dot_v2_dot_service__pb2.Request.SerializeToString,
                response_deserializer=sf_dot_substreams_dot_rpc_dot_v2_dot_service__pb2.Response.FromString,
                _registered_method=True)


class StreamServicer:
    """Stream is the primary service for consuming Substreams data. It provides a real-time
    and historical stream of blockchain blocks processed through Substreams modules.
    """

    def Blocks(self, request, context):
        """Blocks streams processed blockchain data for the requested range, applying the specified
        Substreams modules. Responses include a one-time `SessionInit` message, optional progress
        updates during parallel processing, `BlockScopedData` messages for each processed block,
        `BlockUndoSignal` messages on chain reorganizations, and an `Error` fatal error notification.

        For reliable, exactly-once consumption, see `BlockScopedData.cursor` and
        `BlockUndoSignal.last_valid_cursor`: persisting and resuming from these cursors is the
        foundation of the "never miss a beat" guarantee.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Blocks': grpc.unary_stream_rpc_method_handler(
                    servicer.Blocks,
                    request_deserializer=sf_dot_substreams_dot_rpc_dot_v2_dot_service__pb2.Request.FromString,
                    response_serializer=sf_dot_substreams_dot_rpc_dot_v2_dot_service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sf.substreams.rpc.v2.Stream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sf.substreams.rpc.v2.Stream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Stream:
    """Stream is the primary service for consuming Substreams data. It provides a real-time
    and historical stream of blockchain blocks processed through Substreams modules.
    """

    @staticmethod
    def Blocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sf.substreams.rpc.v2.Stream/Blocks',
            sf_dot_substreams_dot_rpc_dot_v2_dot_service__pb2.Request.SerializeToString,
            sf_dot_substreams_dot_rpc_dot_v2_dot_service__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
